"""add user id in contractor table

Revision ID: 1728807072
Revises: 1728723182
Create Date: 2024-10-13 13:41:12.715050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1728807072'
down_revision: Union[str, None] = '1728723182'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractor', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_contractor_user_id'), 'contractor', ['user_id'], unique=False)
    op.create_foreign_key(None, 'contractor', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contractor', type_='foreignkey')
    op.drop_index(op.f('ix_contractor_user_id'), table_name='contractor')
    op.drop_column('contractor', 'user_id')
    # ### end Alembic commands ###
